[package]
name = "sharppyrs"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.34.3"
sharprs = { git = "https://github.com/FahrenheitResearch/sharprs", version = "0.1.0" }

[dev-dependencies]
eframe = "0.34.3"
egui_kittest = { version = "0.34", features = ["snapshot", "wgpu"] }
serde = "1.0.228"
serde_json = "1.0.150"
