//! Golden tests for [`sharppyrs::DerivedParams`]: every field the full SPC
//! window displays, checked against `testdata/golden_full.json` (generated by
//! running the real Python stack — vendored SHARPpy 1.4.0a5 ConvectiveProfile
//! plus the SHARPpy-Reimagined `sharpmod` derived parameters — on the same
//! HRRR sounding as `testdata/golden.json`, whose `input` block is reused
//! here).
//!
//! Tolerances are engine-level: `TOL_STD` (1e-2 relative) for interpolation/
//! kinematic quantities, `TOL_CAPE` (5e-2) for anything downstream of a
//! parcel lift (sharprs's iterative moist lifts differ from SHARPpy in the
//! last decimals). Fields the engines cannot agree on are explicitly marked
//! EXPECTED-DIVERGENT below — there are two:
//!
//! * `cape_0_3km` — golden holds `null`: the reference sharpmod Profile never
//!   registered a `cape_0_3km` attribute, so its generator recorded missing.
//!   The true SHARPpy value (computed directly from the vendored oracle:
//!   `params.cape(prof, pbot=sfc, ptop=p(3 km AGL)).bplus`) is 89.0371 J/kg,
//!   which is what our port produces and what is asserted here.
//! * `nstp` — golden holds `null` because NSTP needs an ambient surface
//!   vorticity that a bare sounding does not carry; our port also reports
//!   NaN, matching.

use serde_json::Value;
use sharppyrs::{DerivedParams, Profile, SoundingData};

/// Standard engine tolerance (relative, denominator floored at 1).
const TOL_STD: f64 = 1e-2;
/// Tolerance for CAPE-derived values and composite indices.
const TOL_CAPE: f64 = 5e-2;

fn load() -> (Value, Profile, DerivedParams) {
    // Input sounding comes from golden.json (same block the golden.rs tests
    // use); expected derived values come from golden_full.json.
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/testdata/golden.json"
    ))
    .unwrap();
    let g: Value = serde_json::from_str(&raw).unwrap();
    let arr = |k: &str| -> Vec<f64> {
        g["input"][k]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap_or(f64::NAN))
            .collect()
    };
    let data = SoundingData {
        pres: arr("pres"),
        hght: arr("hght"),
        tmpc: arr("tmpc"),
        dwpc: arr("dwpc"),
        wdir: arr("wdir"),
        wspd: arr("wspd"),
        omeg: Some(arr("omeg")),
        latitude: g["latitude"].as_f64(),
        missing: None,
    };
    let prof = Profile::new(data).unwrap();
    let derived = DerivedParams::compute(&prof);

    let raw_full = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/testdata/golden_full.json"
    ))
    .unwrap();
    let gf: Value = serde_json::from_str(&raw_full).unwrap();
    (gf, prof, derived)
}

fn num(v: &Value) -> f64 {
    v.as_f64().unwrap_or(f64::NAN)
}

fn assert_close(actual: f64, expected: f64, tol: f64, what: &str) {
    if expected.is_nan() {
        assert!(actual.is_nan(), "{what}: expected missing, got {actual}");
        return;
    }
    let denom = expected.abs().max(1.0);
    assert!(
        (actual - expected).abs() / denom <= tol,
        "{what}: got {actual}, expected {expected}"
    );
}

/// Compare a `(u, v)` or `(wdir, wspd)` pair against a JSON `[a, b]` array.
fn assert_pair(actual: (f64, f64), expected: &Value, tol: f64, what: &str) {
    assert_close(actual.0, num(&expected[0]), tol, &format!("{what}[0]"));
    assert_close(actual.1, num(&expected[1]), tol, &format!("{what}[1]"));
}

#[test]
fn thermo_block() {
    let (g, _prof, d) = load();
    assert_close(d.pwat, num(&g["pwat"]), TOL_STD, "pwat");
    assert_close(d.k_idx, num(&g["k_idx"]), TOL_STD, "k_idx");
    assert_close(d.tei, num(&g["tei"]), TOL_STD, "tei");
    assert_close(d.mean_mixr, num(&g["mean_mixr"]), TOL_STD, "mean_mixr");
    assert_close(d.low_rh, num(&g["low_rh"]), TOL_STD, "low_rh");
    assert_close(d.mid_rh, num(&g["mid_rh"]), TOL_STD, "mid_rh");
    assert_close(
        d.totals_totals,
        num(&g["totals_totals"]),
        TOL_STD,
        "totals_totals",
    );
    assert_close(d.max_t_f, num(&g["maxT"]), TOL_STD, "maxT");
    // Convective temperature is found by an iterative parcel search in 0.5 C
    // steps; a single-step landing difference is 0.9 F, hence TOL_CAPE.
    assert_close(d.conv_t_f, num(&g["convT"]), TOL_CAPE, "convT");
    assert_close(d.thetae_diff, num(&g["thetae_diff"]), TOL_STD, "thetae_diff");
    assert_close(d.dcape, num(&g["dcape"]), TOL_CAPE, "dcape");
    assert!(d.dcape >= 0.0, "dcape must use the positive display convention");
    assert_close(d.drush_f, num(&g["drush"]), TOL_STD, "drush");
}

#[test]
fn lapse_rates() {
    let (g, _prof, d) = load();
    assert_close(
        d.lapserate_3km,
        num(&g["lapserate_3km"]),
        TOL_STD,
        "lapserate_3km",
    );
    assert_close(
        d.lapserate_3_6km,
        num(&g["lapserate_3_6km"]),
        TOL_STD,
        "lapserate_3_6km",
    );
    assert_close(
        d.lapserate_850_500,
        num(&g["lapserate_850_500"]),
        TOL_STD,
        "lapserate_850_500",
    );
    assert_close(
        d.lapserate_700_500,
        num(&g["lapserate_700_500"]),
        TOL_STD,
        "lapserate_700_500",
    );
    // DELIBERATE DEVIATION from the sharpmod goldens: sharpmod's
    // SFC-500m/SFC-1km rows use plain temperature; every other row of the
    // lapse-rate box (and vendored SHARPpy's params.lapse_rate) uses virtual
    // temperature. We use vtmp for all rows. Oracle values below are from
    // vendored SHARPpy `params.lapse_rate(prof, 0, 500/1000, pres=False)`
    // run on this sounding.
    assert_close(d.lapserate_sfc_500m, 4.908568889523174, TOL_STD, "lapserate_sfc_500m (vtmp)");
    assert_close(d.lapserate_sfc_1km, 6.384036612547792, TOL_STD, "lapserate_sfc_1km (vtmp)");
}

#[test]
fn composite_indices() {
    let (g, _prof, d) = load();
    assert_close(d.esp, num(&g["esp"]), TOL_CAPE, "esp");
    assert_close(d.mmp, num(&g["mmp"]), TOL_CAPE, "mmp");
    assert_close(d.wndg, num(&g["wndg"]), TOL_CAPE, "wndg");
    assert_close(d.dcp, num(&g["dcp"]), TOL_CAPE, "dcp");
    assert_close(d.mburst, num(&g["mburst"]), TOL_CAPE, "mburst");
    assert_close(d.ship, num(&g["ship"]), TOL_CAPE, "ship");
    assert_close(d.right_scp, num(&g["right_scp"]), TOL_CAPE, "right_scp");
    assert_close(d.left_scp, num(&g["left_scp"]), TOL_CAPE, "left_scp");
    assert_close(d.stp_cin, num(&g["stp_cin"]), TOL_CAPE, "stp_cin");
    assert_close(d.stp_fixed, num(&g["stp_fixed"]), TOL_CAPE, "stp_fixed");
    assert_close(d.sweat, num(&g["sweat"]), TOL_STD, "sweat");
    assert_close(d.sig_severe, num(&g["sig_severe"]), TOL_CAPE, "sig_severe");
}

#[test]
fn helicity_and_shear() {
    let (g, _prof, d) = load();
    assert_close(d.srh500, num(&g["srh500"]), TOL_STD, "srh500");
    assert_close(d.srh1km, num(&g["srh1km"][0]), TOL_STD, "srh1km");
    assert_close(d.srh3km, num(&g["srh3km"][0]), TOL_STD, "srh3km");
    assert_close(d.right_esrh, num(&g["right_esrh"][0]), TOL_STD, "right_esrh");
    // The reference records the SFC-500 m shear as a magnitude (kt).
    assert_close(
        (d.sfc_500m_shear.0.powi(2) + d.sfc_500m_shear.1.powi(2)).sqrt(),
        num(&g["derived_shear_sfc_500m"]),
        TOL_STD,
        "sfc_500m_shear magnitude",
    );
    assert_pair(d.sfc_1km_shear, &g["sfc_1km_shear"], TOL_STD, "sfc_1km_shear");
    assert_pair(d.sfc_3km_shear, &g["sfc_3km_shear"], TOL_STD, "sfc_3km_shear");
    assert_pair(d.sfc_6km_shear, &g["sfc_6km_shear"], TOL_STD, "sfc_6km_shear");
    assert_pair(d.sfc_8km_shear, &g["sfc_8km_shear"], TOL_STD, "sfc_8km_shear");
    assert_pair(d.eff_shear, &g["eff_shear"], TOL_STD, "eff_shear");
    assert_pair(d.ebwd, &g["ebwd"], TOL_STD, "ebwd");
    assert_pair(d.lcl_el_shear, &g["lcl_el_shear"], TOL_STD, "lcl_el_shear");
}

#[test]
fn mean_and_sr_winds() {
    let (g, _prof, d) = load();
    assert_pair(
        d.mean_wind_sfc_500m,
        &g["derived_mean_wind_sfc_500m"],
        TOL_STD,
        "mean_wind_sfc_500m",
    );
    assert_pair(d.mean_1km, &g["mean_1km"], TOL_STD, "mean_1km");
    assert_pair(d.mean_3km, &g["mean_3km"], TOL_STD, "mean_3km");
    assert_pair(d.mean_6km, &g["mean_6km"], TOL_STD, "mean_6km");
    assert_pair(d.mean_8km, &g["mean_8km"], TOL_STD, "mean_8km");
    assert_pair(d.mean_eff, &g["mean_eff"], TOL_STD, "mean_eff");
    assert_pair(d.mean_ebw, &g["mean_ebw"], TOL_STD, "mean_ebw");
    assert_pair(d.mean_lcl_el, &g["mean_lcl_el"], TOL_STD, "mean_lcl_el");
    assert_pair(
        d.srw_sfc_500m,
        &g["derived_srw_sfc_500m"],
        TOL_STD,
        "srw_sfc_500m",
    );
    assert_pair(d.srw_1km, &g["right_srw_1km"], TOL_STD, "srw_1km");
    assert_pair(d.srw_3km, &g["right_srw_3km"], TOL_STD, "srw_3km");
    assert_pair(d.srw_6km, &g["right_srw_6km"], TOL_STD, "srw_6km");
    assert_pair(d.srw_8km, &g["right_srw_8km"], TOL_STD, "srw_8km");
    assert_pair(d.srw_4_5km, &g["right_srw_4_5km"], TOL_STD, "srw_4_5km");
    assert_pair(d.srw_eff, &g["srw_eff"], TOL_STD, "srw_eff");
    assert_pair(d.srw_ebw, &g["srw_ebw"], TOL_STD, "srw_ebw");
    assert_pair(d.srw_lcl_el, &g["right_srw_lcl_el"], TOL_STD, "srw_lcl_el");
    assert_pair(d.wind1km, &g["wind1km"], TOL_STD, "wind1km");
    assert_pair(d.wind6km, &g["wind6km"], TOL_STD, "wind6km");
}

#[test]
fn corfidi_critical_angle_brn() {
    let (g, _prof, d) = load();
    let ud = &g["upshear_downshear"];
    assert_close(d.corfidi_up.0, num(&ud[0]), TOL_STD, "corfidi_up u");
    assert_close(d.corfidi_up.1, num(&ud[1]), TOL_STD, "corfidi_up v");
    assert_close(d.corfidi_dn.0, num(&ud[2]), TOL_STD, "corfidi_dn u");
    assert_close(d.corfidi_dn.1, num(&ud[3]), TOL_STD, "corfidi_dn v");
    assert_close(
        d.right_critical_angle,
        num(&g["right_critical_angle"]),
        TOL_STD,
        "right_critical_angle",
    );
    assert_close(
        d.brnshear,
        num(&g["brnshear"]["mupcl"]),
        TOL_STD,
        "brnshear",
    );
}

#[test]
fn reimagined_derived_composites() {
    let (g, _prof, d) = load();
    assert_close(d.ehi_0_1km, num(&g["derived_ehi_0_1km"]), TOL_CAPE, "ehi_0_1km");
    assert_close(d.ehi_0_3km, num(&g["derived_ehi_0_3km"]), TOL_CAPE, "ehi_0_3km");
    assert_close(d.vgp, num(&g["derived_vgp"]), TOL_CAPE, "vgp");
    assert_close(d.peskov, num(&g["derived_peskov"]), TOL_CAPE, "peskov");
    assert_close(d.mcs_index, num(&g["derived_mcs_index"]), TOL_CAPE, "mcs_index");
    assert_close(d.ncape, num(&g["derived_ncape"]), TOL_CAPE, "ncape");
    assert_close(d.lrghail, num(&g["derived_lrghail"]), TOL_CAPE, "lrghail");
    assert_close(d.lscp, num(&g["derived_lscp"]), TOL_CAPE, "lscp");
    assert_close(d.hgz_cape, num(&g["derived_hgz_cape"]), TOL_CAPE, "hgz_cape");
    assert_close(d.wbz_height, num(&g["derived_wbz_height"]), TOL_STD, "wbz_height");
    // ECAPE: analytic Peters et al. (2023) port. The reference solver
    // re-lifts a MetPy-parity pseudoadiabatic parcel for CAPE/LFC/EL; we
    // feed the sharprs MU parcel instead — a ~2.5% engine difference on
    // this sounding, within TOL_CAPE.
    assert_close(d.ecape, num(&g["derived_ecape"]), TOL_CAPE, "ecape");
    assert_close(
        d.modified_sherbe,
        num(&g["derived_modified_sherbe"]),
        TOL_CAPE,
        "modified_sherbe",
    );
    assert_close(
        d.cape_0_6km,
        num(&g["derived_cape_0_6km"]),
        TOL_CAPE,
        "cape_0_6km",
    );

    // nstp: golden holds null (needs an externally supplied surface
    // vorticity); our port reports NaN for a bare sounding — matching.
    assert!(num(&g["derived_nstp"]).is_nan(), "golden nstp should be null");
    assert!(d.nstp.is_nan(), "nstp: expected missing for a bare sounding");

    // EXPECTED-DIVERGENT: cape_0_3km. Golden holds null only because the
    // reference sharpmod Profile never registered the attribute (its 0-6 km
    // twin exists and matches above). The vendored SHARPpy oracle evaluates
    // the same integral to 89.0371 J/kg for this sounding — assert our port
    // against that oracle value instead of the null.
    assert!(num(&g["derived_cape_0_3km"]).is_nan(), "golden cape_0_3km should be null");
    assert!(d.cape_0_3km.is_finite(), "cape_0_3km: expected a finite value");
    assert_close(d.cape_0_3km, 89.03710428872317, 0.10, "cape_0_3km (oracle)");
}

#[test]
fn inferred_temperature_advection() {
    let (g, _prof, d) = load();
    let exp: Vec<f64> = g["temp_adv"]
        .as_array()
        .unwrap()
        .iter()
        .map(num)
        .collect();
    assert_eq!(d.temp_adv.len(), exp.len(), "temp_adv: length mismatch");
    for (i, (a, e)) in d.temp_adv.iter().zip(exp.iter()).enumerate() {
        assert_close(*a, *e, TOL_STD, &format!("temp_adv[{i}]"));
    }
    let bounds = g["temp_adv_bounds"].as_array().unwrap();
    assert_eq!(
        d.temp_adv_bounds.len(),
        bounds.len(),
        "temp_adv_bounds: length mismatch"
    );
    for (i, (a, e)) in d.temp_adv_bounds.iter().zip(bounds.iter()).enumerate() {
        assert_close(a.0, num(&e[0]), TOL_STD, &format!("temp_adv_bounds[{i}].0"));
        assert_close(a.1, num(&e[1]), TOL_STD, &format!("temp_adv_bounds[{i}].1"));
    }
}

#[test]
fn storm_slinky() {
    let (g, _prof, d) = load();
    let xs: Vec<f64> = g["slinky_traj_x"].as_array().unwrap().iter().map(num).collect();
    let ys: Vec<f64> = g["slinky_traj_y"].as_array().unwrap().iter().map(num).collect();
    assert_eq!(d.slinky_traj.len(), xs.len(), "slinky_traj: length mismatch");
    // The trajectory integrates parcel buoyancy from the virtual-temperature
    // trace; sharprs's lift differs from SHARPpy by up to a quarter degree,
    // so positions get the composite tolerance (5% relative) with an
    // absolute floor of 0.5% of the trajectory extent — the x-track crosses
    // zero mid-flight, where a few metres of absolute drift is a huge
    // relative error but sub-pixel on the slinky inset.
    let extent = xs
        .iter()
        .chain(ys.iter())
        .fold(0.0_f64, |m, v| m.max(v.abs()));
    let assert_pos = |a: f64, e: f64, what: &str| {
        let tol = (TOL_CAPE * e.abs()).max(0.005 * extent);
        assert!((a - e).abs() <= tol, "{what}: got {a}, expected {e}");
    };
    for (i, p) in d.slinky_traj.iter().enumerate() {
        assert_pos(p.0, xs[i], &format!("slinky_traj_x[{i}]"));
        assert_pos(p.1, ys[i], &format!("slinky_traj_y[{i}]"));
    }
    assert_close(d.slinky_tilt, num(&g["slinky_theta"]), TOL_STD, "slinky_theta");
}
